# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #Webserver create
  config.vm.define "web" do |web|
     
    #vm config
    web.vm.box = "ubuntu/bionic64"
    web.vm.synced_folder "./sh_web", "/sh_f_web"
    
    #Netconfig
    web.vm.network "private_network", ip: "192.168.1.50",
    virtualbox_intnet: true
    web.vm.network "forwarded_port", guest: 80, host: 11930

    #Vmspecs Web
    web.vm.provider "virtualbox" do |vm_web|
      vm_web.name = "Webserver_M300"
      vm_web.memory = "2048"

  end

   # webserver install
    web.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2
      apt-get install -y php libapache2-mod-php php-mysql
      apt-get install -y mysql-client 
      rm -rf /var/www/html/index.html
      cp /sh_f_web/index.html /var/www/html
      cp /sh_f_web/userinfo.php /var/www/html
    SHELL

  end

    #DBserver create
  config.vm.define "DB" do |db|

     #general config
    db.vm.box = "ubuntu/bionic64"

    #Netconfig
    db.vm.network "private_network", ip: "192.168.1.55",
    virtualbox_intnet: true
    db.vm.network "forwarded_port", guest: 3306, host: 3306

    #Vmspecs DB
    db.vm.provider "virtualbox" do |vb_db|
      vb_db.name = "DBserver_M300"
      vb_db.memory = "2048"


    end

    #Shell Script for DB install and Setup
    db.vm.provision :shell, path: "Database.sh"
  end

end

